version: '3.8'
services:
  backend:
    build: ./brains
    ports:
      - "8000:8000"
    networks:
      - app-network
  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


