# Generated by Django 5.0.8 on 2024-08-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bank_balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
        ),
    ]
